[plugin]
id = "workflow-compiler-plugin"
class = "io.ballerina.stdlib.workflow.compiler.WorkflowCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/workflow-compiler-plugin-@project.version@.jar"

[[dependency]]
path = "../commons/build/libs/workflow-commons-@project.version@.jar"