[package]
org = "ballerina"
name = "workflow"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["workflow"]
repository = "https://github.com/ballerina-platform/module-ballerina-workflow"
license = ["Apache-2.0"]
distribution = "2201.12.10"

[platform.java21]
graalvmCompatible = false

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "workflow-native"
version = "0.1.0"
path = "../native/build/libs/workflow-native-0.1.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "workflow-commons"
version = "0.1.0"
path = "../commons/build/libs/workflow-commons-0.1.0-SNAPSHOT.jar"