[plugin]
id = "workflow-compiler-plugin"
class = "io.ballerina.stdlib.workflow.compiler.WorkflowCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/workflow-compiler-plugin-0.1.0-SNAPSHOT.jar"

[[dependency]]
path = "../commons/build/libs/workflow-commons-0.1.0-SNAPSHOT.jar"